services:
  mysql:
    image: mysql:8.0
    container_name: coupon-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: coupon_db
      MYSQL_ROOT_PASSWORD: password
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - coupon-network

  redis:
    image: redis:7-alpine
    container_name: coupon-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - coupon-network

  kafka:
    image: apache/kafka:latest
    container_name: coupon-kafka
    ports:
      - "9092:9092"
    environment:
      # Apache 공식 이미지 환경 변수 규칙
      # KRaft 모드 적용
      - KAFKA_NODE_ID=0
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=0@coupon-kafka:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # 단일 브로커 최적화
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_DEFAULT_REPLICATION_FACTOR=1
      - KAFKA_NUM_PARTITIONS=3
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - coupon-network

networks:
  coupon-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
  kafka_data: