spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coupon_db?rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      # acks=1
      acks: 1
      retries: 3

    consumer:
      group-id: coupon-issue-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
      consumer:
        # 한 번에 최대 몇 개까지 모아서 가져올지 설정 (예: 100개)
        max-poll-records: 100
      listener:
        # 리스너 타입을 batch로 명시
        type: batch

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: debug
    org.springframework.kafka: info